AlgebraicJulia/CombinatorialSpaces.jl

.github/workflows/tests.yml
Project.toml
src/CombinatorialMaps.jl
src/CombinatorialSpaces.jl
test/CombinatorialMaps.jl
test/runtests.jl

Data structures for rotation graphs and rotation systems, plus the very rudiments of combinatorial maps and hypermaps. Formerly known as `Catlab.Graphs.EmbeddedGraphs`.

Migrate embedded graphs from Catlab

---

Project.toml
src/ArrayUtils.jl
src/SimplicialSets.jl
test/SimplicialSets.jl

This PR implements the discrete exterior derivative, aka coboundary operator, in one and two dimensions. 
It also allows matrices, by default sparse, to be constructed for both boundary and coboundary operators. Whether we will need the matrix form is TBD.

Discrete exterior derivative in two dimensions

---

src/ArrayUtils.jl
src/DualSimplicialSets.jl
src/SimplicialSets.jl
test/DualSimplicialSets.jl
test/SimplicialSets.jl

Add structs `V`, `E`, `Tri` for primal simplices and `DualV`, `DualE`, `DualTri` for dual simplices.
Will be followed by vector types for primal and dual (co)chains. All this should promote readable code and make errors less likely.

Wrap parts of simplicial set for more intuitive dispatch

---

src/ArrayUtils.jl
src/DualSimplicialSets.jl
src/SimplicialSets.jl
test/SimplicialSets.jl

Sequel to #10, adding custom vector types for primal chains and cochains. The boundary and coboundary operations now support these types.

Custom vector types for chains and cochains

---

src/ArrayUtils.jl
src/DualSimplicialSets.jl
test/DualSimplicialSets.jl

Sequel to #22. We have not implemented the flat operator, so the interior product and Lie derivative operators take a 1-form rather than a vector field (i.e., we assume that the flat has already been applied).

Interior product and Lie derivative

---

src/CombinatorialSpaces.jl
src/MeshGraphics.jl
src/MeshInterop.jl
test/MeshGraphics.jl
test/MeshInterop.jl
test/assets/square.stl

With the current mesh tooling, STL formatted mesh files are imported with each triangle disconnected from its neighbors. 
This PR merges these meshes pointwise (points at the same place are merged into a single point) in the conversion to delta sets.

Mesh support for STL files

---

Project.toml
src/CombinatorialSpaces.jl
src/DiscreteExteriorCalculus.jl
src/MeshGraphics.jl
src/MeshInterop.jl
src/SimplicialSets.jl
test/DiscreteExteriorCalculus.jl
test/MeshInterop.jl
test/Project.toml
test/runtests.jl

The name change reflects the more standard terminology (`DiscreteExteriorCalculus` instead of `DualSimplicialSets`) and will also enable a sane organizational scheme when we add a GAT for exterior calculus or a new module for finite element exterior calculus.

Rename module for discrete exterior caclulus

---

src/DiscreteExteriorCalculus.jl
test/DiscreteExteriorCalculus.jl

This PR addresses Issue #37 by creating three Lie Derivative functions for each of the dual forms.
Would it make more sense to add edge-case functions for the `dual_derivative`, `nsimplices`, and other functions that might receive dimension values out of range? This might reduce the amount of code redundancy here.

Lie derivative for dual 0,2-forms

---

src/DiscreteExteriorCalculus.jl
test/DiscreteExteriorCalculus.jl

This PR provides an implementation of the hodge star on primal 1-forms presented in [Ayoub et al 2021](https://www.aimsciences.org/article/doi/10.3934/cpaa.2021062).

Updated Hodge Star for 1-Forms

---

src/SimplicialSets.jl

This PR addresses Issue #41 by changing the `orient_component!` function from recursive to iterative. This should generate equivalent orientations of meshes.

Iterative Implementation for orient_component!

---

Project.toml
src/CombinatorialMaps.jl
src/DiscreteExteriorCalculus.jl
src/MeshGraphics.jl
src/SimplicialSets.jl
test/SimplicialSets.jl

This is the minimal change required for compatibility. I will follow up with another PR to fix the type hierarchy for simplicial sets, using the increased flexibility afforded by struct acsets.

Upgrade to Catlab v0.13

---

src/DiscreteExteriorCalculus.jl
test/DiscreteExteriorCalculus.jl

This PR adds several small fixes, some of which will need further work to be more generalized. The fixes are as follows:
1. Hodge star previously would flip sign if the "positive" orientation of the mesh was towards the negative z-axis. This ensures the diagonal value is always positive (as it should be), and orients the sign of the other products based on this. This favors the z-axis, and should likely be generalized (likely taking advantage of the assigned simplex orientation). [See comment](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/compare/hodge_dev_temp?expand=1#diff-847f28881776a78bfee9c92402f84892c1320618cbab7bb3e849098ba730133eL676-R680)
2. Correct sign for `δ` operator. This is drawn from Gillette's notes (see …

Correct geometric hodge inverse sign and hodge orientation

---

src/DiscreteExteriorCalculus.jl
src/MeshGraphics.jl
src/SimplicialSets.jl
test/SimplicialSets.jl

I've been intending to make this change, enabled by the struct acsets refactor, for some time. It creates a type hierarchy for delta sets of different dimensions, where, for example, one-dimensional delta sets (`AbstractDeltaSet1D`) are distinguished from delta sets having simplices of dimension at least one (`HasDeltaSet1D`). By tightening the types, this PR paves the way for implementing DEC with cubical sets but supporting the same generic functions.
Although none of the interfaces have changed, this PR should probably be considered breaking because it changes the acset schemas for delta sets in the first dimension (`src` and `tgt` are renamed with a scheme consistent with higher dimensions).

Refactor type hierarchy for delta sets

---

src/ExteriorCalculus.jl
test/ExteriorCalculus.jl

This PR adds the definition of FreeExtCalc1D, following the pattern of the definition of FreeExtCalc2D. This is a pretty routine addition, just added in now to assist in defining 1D Decapodes.

ENH: Added 1D FreeExteriorCalculus Definition

---

Project.toml
src/CombinatorialMaps.jl
src/DiscreteExteriorCalculus.jl
src/ExteriorCalculus.jl
src/SimplicialSets.jl

The schemas for delta sets and their dual complexes are now exported following the new naming convention.

Compatibility with Catlab v0.14

---

src/SimplicialSets.jl
test/SimplicialSets.jl

This PR is to track progress on implementing 3D (semi-)simplicial sets in SimplicialSets.jl.
Currently, CombinatorialSpaces.jl supports only 1D and 2D simplicial sets. Although some methods are implemented for arbitrary dimension, such as `orient!`, these methods cannot take advantage of this flexibility due to the lack of higher dimensional simplicial complexes stored as ACSets.
Although there may be some benefits to refactoring SimplicialSets.jl to support arbitrary ND, the diminishing utility for dimensions beyond 3 or 4 for physical applications justifies focusing on a hand-written implementation of 3D simplicial sets for the time being. This is not to say that there is no utility to such an approach. One advantage is that of long-term maintainability at the expense of a larger …

Support 3D Simplicial Sets

---

src/FastDEC.jl
test/Operators.jl

Added back a scaling factor in the wedge 1-1. This is reflected by scaling down the pre-computed coefficients by 2.

Scaled Wedge 1-1

---

docs/src/discrete_exterior_calculus.md
src/DiscreteExteriorCalculus.jl
src/FastDEC.jl
test/DiscreteExteriorCalculus.jl
test/Operators.jl

Previously, we were multiplying by the sign of a dual 2-form after performing the primal-dual 1-1 wedge product at the outermost "test level." It makes sense to curry the sign-accommodation code inside these wedge product operators themselves.
This PR contains two further improvements to the tests: solving for pressure in the test for Euler's equations, and a standalone interior product dual-dual test set.

Move sign inside wedge pd, and solve for pressure in euler

---

docs/Project.toml
docs/src/meshes.md

Temporary fix for #82  to render meshes so that debugging WGLMakie can be placed on a lower priority

Temp replace WGL with Cairo

---

src/FastDEC.jl

This is in response to issue #81. It removes the unecessasy exports and adds a docstring to the FastDEC module.

Fixed up FastDEC

---

src/DiscreteExteriorCalculus.jl
test/DiscreteExteriorCalculus.jl
test/Operators.jl

Close #89 
I only did a quick spot check that the `LLS` matrix computed via the `pinv` method matched the `LLS` matrix for a single triangle for a single dual 1-form. Those matrices were equivalent (save for a ~`1e-17` entry in the `pinv` `LLS` being replaced by a `0.0` entry in the `qr` `LLS`, which I took as a good sign.)
Tests run, but certain tolerance checks no longer pass, including those operators which make use of the `LLSDDSharp` internally.
I need to dive into the test outputs and verify whether it is a tolerance issue, or whether it is due to vector fields no longer satisfying the tangent condition.

Use QR decomposition in DD sharp

---

src/FastDEC.jl

This is meant to replace views in the FastDEC module with regular ACSet accessing. I've also taken the liberty of cleaning up some strange logic.

Update FastDEC after ACSet updates

---

src/DiscreteExteriorCalculus.jl
src/FastDEC.jl
test/DiscreteExteriorCalculus.jl
test/Operators.jl

This is a small PR for converting 0-forms to 1-forms by taking the mean of the data stored on the faces of an edge.
`avg_01_mat` computes a matrix that performs this averaging operation.
`avg_01` constructs and multiplies the given 0-form by that matrix.
Aliases using unicode subscripts are given.
This functionality is quite old but has never been explicitly upstreamed.

Upstream the averaging operator

---

src/FastDEC.jl

Removed some intermediate arrays that are not really needed.

Small improvements to dec_p_derivbound

---

Project.toml
src/DiscreteExteriorCalculus.jl
src/MeshInterop.jl
src/Meshes.jl
test/MeshInterop.jl

Close #99 
For the time being, we can use `TetGen` on 3D Mesh objects from `GeometryBasics`.

3D Mesh IO

---

ext/CombinatorialSpacesCUDAExt.jl

In advance of adding more CUDA versions and wrappers of DEC operators (possibly based off of [KernelAbstractions.jl](https://github.com/JuliaGPU/KernelAbstractions.jl)), it is necessary to clean up the existing code.
For example, the [restrictions](https://github.com/JuliaGPU/GPUCompiler.jl/issues/597) on dispatching CUDA.jl kernel functions led to some redundant code, now deleted. The dispatch of the regular and inverse Hodge stars was also not optimal (, not exploiting the abstract `DiscreteHodge` type for example). Docstrings have also been cleaned. The docstrings for the internal functions to the wedge product are no longer exposed.

Clean CUDA operators

---

Project.toml
src/DiscreteExteriorCalculus.jl
test/DiscreteExteriorCalculus.jl

Currently, we support a flat operation from dual vector-fields to primal one-forms. However, it is sometimes convenient to have a flat operation from primal vector-fields to primal one-forms.
So, this PR adds an implementation of such a flat operation. It is pedagogically simple to understand, and is quick to implement. It assumes that a the values of a primal vector-field can be linearly-interpolated along primal edges. Integrating such a vector-field along one of these primal edges (line-segments) is equivalent to taking the dot-product of the average value of the vector-field with the vector represented by that line segment. This scheme perfectly flattens static vector-fields, of course.
Future PRs can add a cached version of this operation, as in the other "flat matrix" operation, or …

Implement simple linear primal-primal flat

---

src/DiscreteExteriorCalculus.jl
test/DiscreteExteriorCalculus.jl

This PR is a follow-up to PR #115 . The weighting scheme is as before.
Note that this PR requires a user to specify the particular flat type, exactly like in the sharp-matrix case.

Implement matrix version of simple primal-primal flat

---

src/CombinatorialSpaces.jl
src/restrictions.jl
test/restrictions.jl
test/runtests.jl

This PR upstreams code from [this Decapodes commit](https://github.com/AlgebraicJulia/Decapodes.jl/commit/c78dc466ba0ca3644ffbe6d6f646b6f30ca6f60d) which defines restrict/masking functions for boundary conditions. 
While rudimentary, we'd like to develop this code into more sophisticated code for handling boundary conditions, add it to the `default_dec_generate function`, and possibly integrating it with the sheaf-like semantics in [this Catlab/jpf/sheaves branch](https://github.com/AlgebraicJulia/Catlab.jl/tree/jpf/sheaves).

added basic restrict/mask functions and tests

---

src/CombinatorialSpaces.jl
src/FastDEC.jl
src/Multigrid.jl
test/Multigrid.jl

This is meant to wrap up the code that would generate the list of dual meshes. Also leads nicely into a MultigridData constructor. This is mainly aimed for ease-of-use in Decapodes.jl.

Packaging up multigrid meshes

---

src/Meshes.jl
test/Meshes.jl
test/Operators.jl

This PR speeds up `triangulated_grid` generation by around x20 what it was previously and also adds support for `Point3{Float32}`. The order of the points is preserved from the original but the order of the triangles has changed so that they are added left to right and bottom to top.
The main gain in the speed here was using the order of the triangles to speed up the orientation generation significantly. The bottleneck now is the `glue_triangle` section which if improved could lead to another magnitude of speedups.
Below are rough benchmarks run on my local machine.
```julia
This is a 8 by 8 grid
Old: 0.002595 seconds (9.40 k allocations: 1.011 MiB)
New: 0.000109 seconds (1.18 k allocations: 130.406 KiB)
This is a 16 by 16 grid
Old: 0.004915 seconds (38.88 k allocations: 3.983 MiB)
New: …
```

Faster Triangulated Grid Generation

---

Project.toml
src/SimplicialSets.jl
test/SimplicialSets.jl

Add 1D boundary indices accessors

---

src/SimplicialSets.jl
test/SimplicialSets.jl

Previously, the closed star operator would fail to find a compatible method when called on a 1D simplicial set, due to the type signature being too strict. Relaxing this constraint shows the function operates as expected. I also introduce some test cases for Munkres' topological helper functions on the line and the circle.

Relax type signature for closed star

---

src/Multigrid.jl
test/Multigrid.jl

Main speedup is a result of how edge vertices are accessed. Before the pattern was `s[:∂v0][i]` and is now `s[i, :∂v0]`. This method also no longer directly edits a sparse matrix and instead creates it from row, col and value arrays.
Benchmarks are below. Further improvements could be gained by improving the `binary_subdivision` function.
```julia
8 by 8
Old method
0.000775 seconds (7.50 k allocations: 1.420 MiB)
New method
0.000255 seconds (4.18 k allocations: 523.734 KiB)
16 by 16
Old method
0.004468 seconds (31.81 k allocations: 12.524 MiB)
New method
0.000828 seconds (15.68 k allocations: 1.895 MiB)
32 by 32
Old method
0.126676 seconds (132.57 k allocations: 161.549 MiB, 50.90% gc time)
New method
0.003413 seconds (61.26 k allocations: 7.751 MiB)
64 by 64
Old method
0.947636 seconds …
```

Faster binary subdivision map generation

---

src/Multigrid.jl
src/SimplicialSets.jl
test/Multigrid.jl

This PR builds upon PR #137 by also targeting `binary_subdivision` for optimization. By making full use of the simplicial invariants in CombinatorialSpaces, the function is able to directly create the required vertices, edges and triangles instead of relying on the slower `glue_sorted_triangle!` function.
Speedups upon PR creation are already at x2 and I expect better manipulation of ACSet setting can drive further speedups.

Faster Mesh Binary Subdivision

---

src/Multigrid.jl

The resulting `binary_subdivision` function was encountering some performance regressions from the use of batched updates by using iterators. I've kept the batching but instead use StaticArrays to avoid intermediate allocations. While the resulting code isn't quite as a fast as the original, non-batched code, it is fairly close.
For triangulated_grid, 150 x 150 length, with 1 grid spacing:
Original (non-batched)
31.626 ms (1239233 allocations: 129.83 MiB)
Original (batched with Iterators)
53.896 ms (2320433 allocations: 173.13 MiB)
Current (batched with SVector)
35.341 ms (1239233 allocations: 129.83 MiB)

Use StaticArrays in Binary Subdivision

---

src/Multigrid.jl
test/Multigrid.jl

For testing purposes, it’s convenient to have a trivial/ unit geometric map series of identity maps. So, the “unary” subdivision scheme is implemented, and not exported.

Implement trivial unary subdivision

---

docs/src/grid_laplace.md
src/Multigrid.jl

The docs action shows as a green checkmark, but the docs build is currently failing. This is likely due to [this line](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/c6c93df572ae35db047b7a100c4fa4ad54763120/docs/src/grid_laplace.md?plain=1#L332):
> using Pkg; Pkg.activate("docs") #hide ##XX: testing
which appears to activate a new "docs" directory in "docs/build". i.e. "docs/build/docs", which then elides the surrounding error messages from the parent originals docs environment.

Update MG docs to use MultigridData

---

src/Meshes.jl
test/DiscreteExteriorCalculus.jl
test/MeshInterop.jl
test/Operators.jl

As mentioned in the review of PR #169 , move the TetGen README mesh introduced in PR #100 from tests to src, due to repeated usage and the addition of TetGen as a direct dependency.

Move TetGen README mesh to src

---

src/Multigrid.jl
test/Multigrid.jl

Previously, the restriction maps\* in multigrid code were allocated by taking the transpose of the corresponding prolongation matrix and dividing by a fixed constant per subdivision scheme. Unary subdivision would divide rows by 1, binary by 4, and cubic by 9.
However, this performance optimization is not necessary, and can lead to higher residuals than necessary.
So, this PR row-normalizes each restriction matrix. Avoiding footguns around row-normalization in Julia, we follow community best practices linked in the code. The methods of the former API which parameterize by subdivision scheme are kept to maintain backwards compatibility.
\* See https://math.mit.edu/classes/18.086/2006/am63.pdf for example

Normalize by row-sums

---

Project.toml
ext/CombinatorialSpacesDelaunayTriangulationExt.jl
test/MeshInterop.jl

This PR adds a small interop function for the [DelaunayTriangulation.jl](https://github.com/JuliaGeometry/DelaunayTriangulation.jl) package. A user would be expected to use DelaunayTriangulation to generate a specific 2D mesh that they desire and then use the interop function to port it to an `EmbeddedDeltaSet2D`. 
The advantages are the ability to quickly generate a mesh given only a set of desired points, have it be Delaunay (which is shown to work well in general for DEC), and allow for mesh refinement (both unconstrained and constrained). 
This PR only adds DelaunayTriangulation as an extension so there is no downside for users not using this feature.

Add support for DelaunayTriangulation.jl
