AlgebraicJulia/CombinatorialSpaces.jl

Project.toml, src/CombinatorialSpaces.jl, src/SimplicialSets.jl, test/SimplicialSets.jl, test/runtests.jl
This provides the basic data structure and interface. Next up should be orientation, chains and cochains, and the boundary and coboundary (exterior derivative) operators.
=> 2D semi-simplicial sets

Project.toml, src/ArrayUtils.jl, src/CombinatorialSpaces.jl, src/SimplicialSets.jl, test/SimplicialSets.jl
*Oriented* simplicial sets in one and two dimensions, with boundary operator on individual simplices, as well as chains (linear combinations of oriented simplices).
=> 2D oriented simplicial sets

.github/workflows/docs.yml, docs/.gitignore, docs/Project.toml, docs/make.jl, docs/src/combinatorial_maps.md, docs/src/index.md, docs/src/simplicial_sets.md
Builds the API docs and is otherwise a stub.
=> Set up Documenter.jl

Project.toml, src/ArrayUtils.jl, src/CombinatorialSpaces.jl, src/DualSimplicialSets.jl, src/SimplicialSets.jl, test/DualSimplicialSets.jl, test/SimplicialSets.jl, test/runtests.jl
In dimension one:
- construct the dual complex
- orient the dual edges using primal edge orientations
No embedding in Euclidean space yet.
=> Dual complexes for 1D delta sets

src/ArrayUtils.jl, src/DualSimplicialSets.jl, src/SimplicialSets.jl, test/DualSimplicialSets.jl, test/SimplicialSets.jl
Sequel to #8. I am fairly, but not completely, sure that I got the orientations right.
=> Dual complexes for 2D delta sets

Project.toml, src/DualSimplicialSets.jl, src/SimplicialSets.jl, test/DualSimplicialSets.jl, test/SimplicialSets.jl
Supports simplicial subdivision using the:
- barycenter
- circumcenter
- incenter
=> Embedded delta sets and their dual complexes, in 1D and 2D

src/ArrayUtils.jl, src/DualSimplicialSets.jl, src/SimplicialSets.jl, test/DualSimplicialSets.jl, test/SimplicialSets.jl
Next up: the codifferential and Laplace operators.
=> Hodge star operator in 1D and 2D

docs/src/dual_complexes.md, src/DualSimplicialSets.jl, src/SimplicialSets.jl, test/DualSimplicialSets.jl, test/SimplicialSets.jl
Plus some refactoring of how the DEC operators are dispatched.
=> Codifferential and Laplace-Beltrami operators in 1D and 2D

src/DualSimplicialSets.jl, src/SimplicialSets.jl, test/SimplicialSets.jl
@bosonbaas, this should be useful for you.
=> Consistently orient simplices in a connected component

README.md, docs/make.jl, docs/src/index.md, src/SimplicialSets.jl
A first step in fleshing out the docs to include more than the API reference.
=> Expand README and write overview for the docs

src/SimplicialSets.jl, test/SimplicialSets.jl
=> Consistently orient all simplices

docs/make.jl, docs/src/combinatorial_maps.md, docs/src/dual_complexes.md, docs/src/meshes.md, docs/src/simplicial_sets.md, src/CombinatorialSpaces.jl, src/MeshInterop.jl, src/SimplicialSets.jl
Introduces delta sets (semi-simplicial sets) and our API for them. Only the basic combinatorics are covered; oriented and embedded delta sets will be the topic of a future PR.
=> Introductory docs on delta sets

src/DualSimplicialSets.jl, src/SimplicialSets.jl, test/DualSimplicialSets.jl
Specifically, this is the primal-primal wedge product described in Section 7.1 of Hirani's PhD thesis.
=> Wedge product in dimensions one and two

src/ArrayUtils.jl, src/DualSimplicialSets.jl, test/DualSimplicialSets.jl
Implements the dual-primal-primal (DPP) flat operator in the two-dimensional case.
=> DPP flat operator in two dimensions

src/DualSimplicialSets.jl, src/SimplicialSets.jl, test/DualSimplicialSets.jl
Following (Hirani, 2003) and (Desbrun et al, 2005) but see the caveats in the docstring.
=> Discrete primal-primal sharp operator

src/DualSimplicialSets.jl
This PR slightly modifies the existing sharp operator so that it more closely aligns with Hirani's definition of the primal-primal sharp operator.
=> Sharp Operator Update

src/CombinatorialSpaces.jl, src/DiscreteExteriorCalculus.jl, src/ExteriorCalculus.jl, test/DiscreteExteriorCalculus.jl, test/ExteriorCalculus.jl, test/runtests.jl
GATs for the exterior calculus specialized to dimensions 1 and 2.
=> GAT for exterior calculus

src/DiscreteExteriorCalculus.jl, src/ExteriorCalculus.jl, test/DiscreteExteriorCalculus.jl
Implements in the Laplace-de Rham operator for the DEC and adds both the Laplace-Beltrami and Laplace-de Rham operators to the exterior calculus GAT.
=> Laplace-de Rham operator

.github/workflows/codecov.yml, .github/workflows/docs.yml, .github/workflows/tests.yml, src/ArrayUtils.jl, src/DiscreteExteriorCalculus.jl
It is also used for `meet` in Catlab.
=> Fix name conflict with wedge product operator

Project.toml, docs/make.jl, src/ExteriorCalculus.jl
Package works on Catlab#main. Do not merge until after next Catlab release.
Closes #62.
=> Compatibility with GATlab

src/SimplicialSets.jl
=> Type chains in link operator

.buildkite/jobscript.sh, .buildkite/pipeline.yml
=> Update Buildkite CI pipeline

src/Multigrid.jl, test/Multigrid.jl
=> Implement cubic subdivision

src/Multigrid.jl
This first commit rearranges the source code. The multiple dispatch/ "Julian nonsense" code was scattered in with the definitions of subdivision schemes and multigrid algorithms. The readability is improved.
=> Reorganize multigrid API

src/DiscreteExteriorCalculus.jl, test/DiscreteExteriorCalculus.jl
=> Add alias for inverse hodge star

Project.toml
Adding additional authors to the Project.toml
=> DOC: update authors list

src/SimplicialSets.jl, test/SimplicialSets.jl
=> Print summary statistics for large meshes

src/Multigrid.jl, test/Multigrid.jl
=> Change default smoothing to 0 iterations when `steps` is 0
